services:
  accounts:
    image: "sorinpopteanu/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - trackitu

  rooms:
    image: "sorinpopteanu/rooms"
    container_name: rooms-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - trackitu

networks:
  trackitu:
    driver: "bridge"